SELECT '1 Fund' AS gl_segment FROM DUAL
UNION SELECT '2 Natural Account' FROM DUAL
UNION SELECT '3 Cost Center' FROM DUAL
UNION SELECT '4 Project' FROM DUAL
UNION SELECT '5 Source of Funds' FROM DUAL
UNION SELECT '6 Task' FROM DUAL
