SELECT '01 JUL.' AS accounting_period FROM dual
UNION SELECT '02 AUG.' FROM dual
UNION SELECT '03 SEP.' FROM dual
UNION SELECT '04 OCT.' FROM dual
UNION SELECT '05 NOV.' FROM dual
UNION SELECT '06 DEC.' FROM dual
UNION SELECT '07 JAN.' FROM dual
UNION SELECT '08 FEB.' FROM dual
UNION SELECT '09 MAR.' FROM dual
UNION SELECT '10 APR.' FROM dual
UNION SELECT '11 MAY.' FROM dual
UNION SELECT '12 JUN.' FROM dual
UNION SELECT '13 ADJ1.' FROM dual
UNION SELECT '14 ADJ2.' FROM dual